# Generated by Django 2.0.3 on 2018-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_datetime', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('high_under_ground', models.FloatField()),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_vector_direction', models.CharField(max_length=2)),
            ],
        ),
    ]
