# Generated by Django 2.0.3 on 2018-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField()),
                ('record_numbers', models.IntegerField()),
                ('sum_temperature', models.FloatField()),
                ('sum_wind_speed', models.FloatField()),
                ('avg_temperature', models.FloatField()),
                ('avg_wind_speed', models.FloatField()),
                ('north_direction', models.IntegerField()),
                ('south_direction', models.IntegerField()),
                ('west_direction', models.IntegerField()),
                ('east_direction', models.IntegerField()),
                ('north_east_direction', models.IntegerField()),
                ('north_west_direction', models.IntegerField()),
                ('south_east_direction', models.IntegerField()),
                ('south_west_direction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherStats',
        ),
    ]
