# Generated by Django 2.0.3 on 2018-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20180325_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstatsmodel',
            name='most_windy_direction',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
